USE [master]
GO
/****** Object:  Database [OT_Assessment_DB]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE DATABASE [OT_Assessment_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OT_Assessment_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\OT_Assessment_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OT_Assessment_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\OT_Assessment_DB_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [OT_Assessment_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OT_Assessment_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OT_Assessment_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OT_Assessment_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OT_Assessment_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [OT_Assessment_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OT_Assessment_DB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [OT_Assessment_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [OT_Assessment_DB] SET  MULTI_USER 
GO
ALTER DATABASE [OT_Assessment_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OT_Assessment_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OT_Assessment_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OT_Assessment_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OT_Assessment_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OT_Assessment_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'OT_Assessment_DB', N'ON'
GO
ALTER DATABASE [OT_Assessment_DB] SET QUERY_STORE = OFF
GO
USE [OT_Assessment_DB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 11/22/2024 1:31:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
    [MigrationId] [nvarchar](150) NOT NULL,
    [ProductVersion] [nvarchar](32) NOT NULL,
    CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED
(
[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[Games]    Script Date: 11/22/2024 1:31:33 AM ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [dbo].[Games](
    [Id] [uniqueidentifier] NOT NULL,
    [ProviderId] [uniqueidentifier] NOT NULL,
    [Name] [nvarchar](450) NOT NULL,
    [Theme] [nvarchar](max) NOT NULL,
    CONSTRAINT [PK_Games] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[Players]    Script Date: 11/22/2024 1:31:33 AM ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [dbo].[Players](
    [Id] [uniqueidentifier] NOT NULL,
    [Username] [nvarchar](450) NOT NULL,
    CONSTRAINT [PK_Players] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[Providers]    Script Date: 11/22/2024 1:31:33 AM ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [dbo].[Providers](
    [Id] [uniqueidentifier] NOT NULL,
    [ProviderName] [nvarchar](450) NOT NULL,
    CONSTRAINT [PK_Providers] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[TopPlayersBySpend]    Script Date: 11/22/2024 1:31:33 AM ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [dbo].[TopPlayersBySpend](
    [AccountId] [uniqueidentifier] NOT NULL,
    [Username] [nvarchar](max) NOT NULL,
    [TotalAmountSpend] [decimal](18, 2) NOT NULL,
    CONSTRAINT [PK_TopPlayersBySpend] PRIMARY KEY CLUSTERED
(
[AccountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[Wagers]    Script Date: 11/22/2024 1:31:33 AM ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [dbo].[Wagers](
    [Id] [uniqueidentifier] NOT NULL,
    [Amount] [decimal](18, 2) NOT NULL,
    [CreatedDateTime] [datetime2](7) NOT NULL,
    [NumberOfBets] [int] NOT NULL,
    [PlayerId] [uniqueidentifier] NOT NULL,
    [GameId] [uniqueidentifier] NULL,
    [ProviderId] [uniqueidentifier] NULL,
    CONSTRAINT [PK_Wagers] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
    SET ANSI_PADDING ON
    GO
/****** Object:  Index [IX_Games_Name]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_Games_Name] ON [dbo].[Games]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Games_ProviderId]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_Games_ProviderId] ON [dbo].[Games]
(
	[ProviderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Players_Username]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_Players_Username] ON [dbo].[Players]
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Providers_ProviderName]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_Providers_ProviderName] ON [dbo].[Providers]
(
	[ProviderName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Wagers_GameId]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_Wagers_GameId] ON [dbo].[Wagers]
(
	[GameId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Wagers_PlayerId]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_Wagers_PlayerId] ON [dbo].[Wagers]
(
	[PlayerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Wagers_ProviderId]    Script Date: 11/22/2024 1:31:33 AM ******/
CREATE NONCLUSTERED INDEX [IX_Wagers_ProviderId] ON [dbo].[Wagers]
(
	[ProviderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Games]  WITH CHECK ADD  CONSTRAINT [FK_Games_Providers_ProviderId] FOREIGN KEY([ProviderId])
    REFERENCES [dbo].[Providers] ([Id])
    ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Games] CHECK CONSTRAINT [FK_Games_Providers_ProviderId]
    GO
ALTER TABLE [dbo].[Wagers]  WITH CHECK ADD  CONSTRAINT [FK_Wagers_Games_GameId] FOREIGN KEY([GameId])
    REFERENCES [dbo].[Games] ([Id])
    GO
ALTER TABLE [dbo].[Wagers] CHECK CONSTRAINT [FK_Wagers_Games_GameId]
    GO
ALTER TABLE [dbo].[Wagers]  WITH CHECK ADD  CONSTRAINT [FK_Wagers_Players_PlayerId] FOREIGN KEY([PlayerId])
    REFERENCES [dbo].[Players] ([Id])
    ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Wagers] CHECK CONSTRAINT [FK_Wagers_Players_PlayerId]
    GO
ALTER TABLE [dbo].[Wagers]  WITH CHECK ADD  CONSTRAINT [FK_Wagers_Providers_ProviderId] FOREIGN KEY([ProviderId])
    REFERENCES [dbo].[Providers] ([Id])
    GO
ALTER TABLE [dbo].[Wagers] CHECK CONSTRAINT [FK_Wagers_Providers_ProviderId]
    GO
/****** Object:  StoredProcedure [dbo].[GetTopPlayersBySpend]    Script Date: 11/22/2024 1:31:33 AM ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO

CREATE PROCEDURE [dbo].[GetTopPlayersBySpend] 
 @Count INT
AS
BEGIN
SELECT TOP(@Count) Sum(wagers.amount) AS totalAmountSpend,
                         playerid           AS accountId,
                         players.username
FROM   wagers
    LEFT JOIN players
ON wagers.playerid = players.id
GROUP  BY playerid,
    players.username
ORDER  BY totalamountspend DESC
END;

GO
USE [master]
GO
ALTER DATABASE [OT_Assessment_DB] SET  READ_WRITE 
GO
